name: CalculadoraVenta

options:
  bundleIdPrefix: com.tecsup
  deploymentTarget:
    iOS: "15.0"

targets:
  CalculadoraVenta:
    type: application
    platform: iOS

    sources:
      - path: .

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tecsup.CalculadoraVenta
        SWIFT_VERSION: "5.0"
